#!/bin/bash

declare -a urls=("https://www.redhat.com" "https://www.oracle.com" "https://www.ibm.com")
 
archivo="urls.csv"
printf "%s\n" "$(date)" > "$archivo"  
for url in "${urls[@]}"; do
    estado=$(curl -m 10 -s -I "$url" | head -n 1 | awk '{print $2}')
    printf "%s,%s\n" "$url" "$estado" >> "$archivo"  
done

column -s, -t < "$archivo" 

